### ISSUE TITLE
Invalid HTML in index.html breaks html-loader in webpack

### ISSUE THREAD

**Issue by sflanker** [dominictarr/d64#3]
I get the following error from webpack when trying to bundle an app that uses html-loader and depends on d64:

    ERROR in ./node_modules/d64/index.html
    Module build failed: Error: Parse Error: <>\',-.'</span><span class=w>
        at new HTMLParser (/Users/paul/dev/test/aurelia-sandbox/node_modules/html-minifier/src/htmlparser.js:235:13)
        at minify (/Users/paul/dev/test/aurelia-sandbox/node_modules/html-minifier/src/htmlminifier.js:944:3)
        at Object.exports.minify (/Users/paul/dev/test/aurelia-sandbox/node_modules/html-minifier/src/htmlminifier.js:1299:10)
        at Object.module.exports (/Users/paul/dev/test/aurelia-sandbox/node_modules/html-loader/index.js:128:26)
     @ ./node_modules/d64/index.js
     @ ./node_modules/uuid-base64/index.js
     @ ./src/app.ts

**Comment by dominictarr** [comment]
this is a bug in `html-loader`. d64 is just a javascript library and that html shouldn't be included.

**Comment by sflanker** [comment]
I agree that `index.html` shouldn't be included in your NPM package. Can you issue a new release that does not include it?

Can you reference a specific bug # in `html-loader`? It seems like it's doing its job, and looking at the content of the html file in your package it is definitely invalid. It includes a number of unescaped reserved characters including & < and >

**Comment by sflanker** [comment]
I've discovered that other packages also commonly include their documentation html and have this same problem, so it does seem like webpack/html-loader should be handling this scenario more gracefully. However it would be nice if that html were valid.
